import NextAuthProvider from "@/providers/nextAuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import RootLoading from "./loading";
import { cn } from "@/lib/utils";
import { Suspense } from "react";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar/Navbar";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "overflow-x-hidden bg-background font-sans antialiased",
          roboto.className
        )}
      >
        <NextAuthProvider>
          <Navbar />
          <Suspense fallback={<RootLoading />}>
            <main className="w-full min-h-screen p-10">{children}</main>
            <Toaster />
          </Suspense>
        </NextAuthProvider>
      </body>
    </html>
  );
}
